### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by GhostEsso** [dagmawiii03/mobile-Portfolio-setup#11]
- Good Job :+1:  @dagmawiii03, please, there is a problem with your MIT, when I click on it, it sends me a 404 page. Normally, it should refer to the license.
![image](https://user-images.githubusercontent.com/114746721/225544161-b6299937-34c7-4f0b-9ea4-80be6ad141cd.png)

**Comment by Bellagirl-maker** [comment]
I think you have done a great job on this project. keep it up

**Comment by qusai122** [comment]
**Good job so far, done There are some issues that you need to work on**

- the navbar text color doesn't match the design
- can you add some animation to make your page more interaction
- as my colleague mentioned you need to fix the MIT

Cheers and Happy coding!👏👏👏
